//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManagementUtil.ServiceReference_JPush {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_JPush.WebCardHolderSoap")]
    public interface WebCardHolderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CardHolder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CardHolder(string token, string cardType, string taskId, string encryption, string DataTypeCode, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CardHolder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CardHolderAsync(string token, string cardType, string taskId, string encryption, string DataTypeCode, string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebCardHolderSoapChannel : FileManagementUtil.ServiceReference_JPush.WebCardHolderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebCardHolderSoapClient : System.ServiceModel.ClientBase<FileManagementUtil.ServiceReference_JPush.WebCardHolderSoap>, FileManagementUtil.ServiceReference_JPush.WebCardHolderSoap {
        
        public WebCardHolderSoapClient() {
        }
        
        public WebCardHolderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebCardHolderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebCardHolderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebCardHolderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CardHolder(string token, string cardType, string taskId, string encryption, string DataTypeCode, string content) {
            return base.Channel.CardHolder(token, cardType, taskId, encryption, DataTypeCode, content);
        }
        
        public System.Threading.Tasks.Task<string> CardHolderAsync(string token, string cardType, string taskId, string encryption, string DataTypeCode, string content) {
            return base.Channel.CardHolderAsync(token, cardType, taskId, encryption, DataTypeCode, content);
        }
    }
}
