//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManagementUtil.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.WxServiceSoap")]
    public interface WxServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 secret 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        FileManagementUtil.ServiceReference3.SendMessageResponse SendMessage(FileManagementUtil.ServiceReference3.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<FileManagementUtil.ServiceReference3.SendMessageResponse> SendMessageAsync(FileManagementUtil.ServiceReference3.SendMessageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 secret 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage_Param2", ReplyAction="*")]
        FileManagementUtil.ServiceReference3.SendMessage_Param2Response SendMessage_Param2(FileManagementUtil.ServiceReference3.SendMessage_Param2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage_Param2", ReplyAction="*")]
        System.Threading.Tasks.Task<FileManagementUtil.ServiceReference3.SendMessage_Param2Response> SendMessage_Param2Async(FileManagementUtil.ServiceReference3.SendMessage_Param2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public FileManagementUtil.ServiceReference3.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(FileManagementUtil.ServiceReference3.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string secret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string templateid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string opeinid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string occurtime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string linkUrl;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string secret, string templateid, string title, string opeinid, string content, string occurtime, string remark, string linkUrl) {
            this.secret = secret;
            this.templateid = templateid;
            this.title = title;
            this.opeinid = opeinid;
            this.content = content;
            this.occurtime = occurtime;
            this.remark = remark;
            this.linkUrl = linkUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileManagementUtil.ServiceReference3.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(FileManagementUtil.ServiceReference3.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(string SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessage_Param2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage_Param2", Namespace="http://tempuri.org/", Order=0)]
        public FileManagementUtil.ServiceReference3.SendMessage_Param2RequestBody Body;
        
        public SendMessage_Param2Request() {
        }
        
        public SendMessage_Param2Request(FileManagementUtil.ServiceReference3.SendMessage_Param2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessage_Param2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string secret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string templateid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string opeinid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string keyword1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string keyword2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string linkUrl;
        
        public SendMessage_Param2RequestBody() {
        }
        
        public SendMessage_Param2RequestBody(string secret, string templateid, string title, string opeinid, string keyword1, string keyword2, string remark, string linkUrl) {
            this.secret = secret;
            this.templateid = templateid;
            this.title = title;
            this.opeinid = opeinid;
            this.keyword1 = keyword1;
            this.keyword2 = keyword2;
            this.remark = remark;
            this.linkUrl = linkUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessage_Param2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage_Param2Response", Namespace="http://tempuri.org/", Order=0)]
        public FileManagementUtil.ServiceReference3.SendMessage_Param2ResponseBody Body;
        
        public SendMessage_Param2Response() {
        }
        
        public SendMessage_Param2Response(FileManagementUtil.ServiceReference3.SendMessage_Param2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessage_Param2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMessage_Param2Result;
        
        public SendMessage_Param2ResponseBody() {
        }
        
        public SendMessage_Param2ResponseBody(string SendMessage_Param2Result) {
            this.SendMessage_Param2Result = SendMessage_Param2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WxServiceSoapChannel : FileManagementUtil.ServiceReference3.WxServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WxServiceSoapClient : System.ServiceModel.ClientBase<FileManagementUtil.ServiceReference3.WxServiceSoap>, FileManagementUtil.ServiceReference3.WxServiceSoap {
        
        public WxServiceSoapClient() {
        }
        
        public WxServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WxServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WxServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WxServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileManagementUtil.ServiceReference3.SendMessageResponse FileManagementUtil.ServiceReference3.WxServiceSoap.SendMessage(FileManagementUtil.ServiceReference3.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(string secret, string templateid, string title, string opeinid, string content, string occurtime, string remark, string linkUrl) {
            FileManagementUtil.ServiceReference3.SendMessageRequest inValue = new FileManagementUtil.ServiceReference3.SendMessageRequest();
            inValue.Body = new FileManagementUtil.ServiceReference3.SendMessageRequestBody();
            inValue.Body.secret = secret;
            inValue.Body.templateid = templateid;
            inValue.Body.title = title;
            inValue.Body.opeinid = opeinid;
            inValue.Body.content = content;
            inValue.Body.occurtime = occurtime;
            inValue.Body.remark = remark;
            inValue.Body.linkUrl = linkUrl;
            FileManagementUtil.ServiceReference3.SendMessageResponse retVal = ((FileManagementUtil.ServiceReference3.WxServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileManagementUtil.ServiceReference3.SendMessageResponse> FileManagementUtil.ServiceReference3.WxServiceSoap.SendMessageAsync(FileManagementUtil.ServiceReference3.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileManagementUtil.ServiceReference3.SendMessageResponse> SendMessageAsync(string secret, string templateid, string title, string opeinid, string content, string occurtime, string remark, string linkUrl) {
            FileManagementUtil.ServiceReference3.SendMessageRequest inValue = new FileManagementUtil.ServiceReference3.SendMessageRequest();
            inValue.Body = new FileManagementUtil.ServiceReference3.SendMessageRequestBody();
            inValue.Body.secret = secret;
            inValue.Body.templateid = templateid;
            inValue.Body.title = title;
            inValue.Body.opeinid = opeinid;
            inValue.Body.content = content;
            inValue.Body.occurtime = occurtime;
            inValue.Body.remark = remark;
            inValue.Body.linkUrl = linkUrl;
            return ((FileManagementUtil.ServiceReference3.WxServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileManagementUtil.ServiceReference3.SendMessage_Param2Response FileManagementUtil.ServiceReference3.WxServiceSoap.SendMessage_Param2(FileManagementUtil.ServiceReference3.SendMessage_Param2Request request) {
            return base.Channel.SendMessage_Param2(request);
        }
        
        public string SendMessage_Param2(string secret, string templateid, string title, string opeinid, string keyword1, string keyword2, string remark, string linkUrl) {
            FileManagementUtil.ServiceReference3.SendMessage_Param2Request inValue = new FileManagementUtil.ServiceReference3.SendMessage_Param2Request();
            inValue.Body = new FileManagementUtil.ServiceReference3.SendMessage_Param2RequestBody();
            inValue.Body.secret = secret;
            inValue.Body.templateid = templateid;
            inValue.Body.title = title;
            inValue.Body.opeinid = opeinid;
            inValue.Body.keyword1 = keyword1;
            inValue.Body.keyword2 = keyword2;
            inValue.Body.remark = remark;
            inValue.Body.linkUrl = linkUrl;
            FileManagementUtil.ServiceReference3.SendMessage_Param2Response retVal = ((FileManagementUtil.ServiceReference3.WxServiceSoap)(this)).SendMessage_Param2(inValue);
            return retVal.Body.SendMessage_Param2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileManagementUtil.ServiceReference3.SendMessage_Param2Response> FileManagementUtil.ServiceReference3.WxServiceSoap.SendMessage_Param2Async(FileManagementUtil.ServiceReference3.SendMessage_Param2Request request) {
            return base.Channel.SendMessage_Param2Async(request);
        }
        
        public System.Threading.Tasks.Task<FileManagementUtil.ServiceReference3.SendMessage_Param2Response> SendMessage_Param2Async(string secret, string templateid, string title, string opeinid, string keyword1, string keyword2, string remark, string linkUrl) {
            FileManagementUtil.ServiceReference3.SendMessage_Param2Request inValue = new FileManagementUtil.ServiceReference3.SendMessage_Param2Request();
            inValue.Body = new FileManagementUtil.ServiceReference3.SendMessage_Param2RequestBody();
            inValue.Body.secret = secret;
            inValue.Body.templateid = templateid;
            inValue.Body.title = title;
            inValue.Body.opeinid = opeinid;
            inValue.Body.keyword1 = keyword1;
            inValue.Body.keyword2 = keyword2;
            inValue.Body.remark = remark;
            inValue.Body.linkUrl = linkUrl;
            return ((FileManagementUtil.ServiceReference3.WxServiceSoap)(this)).SendMessage_Param2Async(inValue);
        }
    }
}
